name: PR custom action test

on: 
  pull_request:
    types: [opened, reopened, synchronize]
  push: [main]

jobs:
  automate-pr-actions:
    runs-on: ubuntu-latest
    name: Automates operations performed on PR
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js                            #will install node version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm ci
        
      - name: Run your custom action
        uses: ./action.yml
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: node index.js
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          token: ${{ secrets.REPO_TOKEN }}

