name: Testing PR to main branch!
on:
  push:
    branches:
      - pr-test
jobs:
  build:
     runs-on: ubuntu-latest
     env:
       token: ${{ secrets.PAT }}
    steps:
       - name: Testing
         run: echo 'This is a test branch!'
