name: PR custom action tests

on: 
 pull_request:
   types: [opened, reopened, synchronize]
   branches: main
  # push: 
  #   branches: 
  #   - main

jobs:
  automate-pr-actions:
    runs-on: ubuntu-latest
    name: Automates operations performed on PR
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js                            #will install node version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: |
          npm install
          npm ci

      - name: Checkout code
        uses: actions/checkout@v2
        with: 
         ref: pr-test
        
      - name: Add package-lock.json file
        run: |
         git config --global user.email tanvinaxane@gmail.com
         git config --global user.name ${{ github.repository_owner }}
         git checkout pr-test
         git add .
         git pull origin pr-test
         git status
         git commit -m "Commit changes"
         git push -u origin main

      - name: Run your custom action
        uses: ./custom-action-test/action.yml
        env:
          PAT: ${{ secrets.PAT }}
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          token: ${{ secrets.PAT }}

      - name: Execute JS code
        run: node index.js
